services:
  client:
    container_name: react
    build: client/
    ports:
      - "3001:3001"
    volumes:
      - /usr/src/app/node_modules
      - ./client/:/usr/src/app/
  server:
    container_name: flask
    build: server/
    volumes:
      - ./server/:/usr/src/app/
    environment:
      - FLASK_APP=flask_app
      - FLASK_DEBUG=1