services:
  client:
    container_name: client
    build: client/
    ports:
      - "3000:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./client/:/usr/src/app/
  server:
    container_name: server
    build: server/
    volumes:
      - ./server/:/usr/src/app/
    environment:
      - FLASK_APP=flask_app
      - FLASK_DEBUG=1